# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  cavemem = {
    pname = "cavemem";
    version = "v0.2.1";
    src = fetchFromGitHub {
      owner = "JuliusBrussee";
      repo = "cavemem";
      rev = "v0.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-0YkpwaBYyH/nJCV0Y2EvaFL1KEvVtgf/tN2h1azwdNg=";
    };
  };
  cord-nvim = {
    pname = "cord-nvim";
    version = "v2.3.29";
    src = fetchFromGitHub {
      owner = "vyfor";
      repo = "cord.nvim";
      rev = "v2.3.29";
      fetchSubmodules = false;
      sha256 = "sha256-zQNkfw3YrEvs9JMgC5UnVE09S/bCIRT+R1j4KaAA0Kc=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-zQNkfw3YrEvs9JMgC5UnVE09S_bCIRT+R1j4KaAA0Kc=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  equibop = {
    pname = "equibop";
    version = "328e2ce76216e27a2d8e78d4723014adef079803";
    src = fetchFromGitHub {
      owner = "Equicord";
      repo = "Equicord";
      rev = "328e2ce76216e27a2d8e78d4723014adef079803";
      fetchSubmodules = false;
      sha256 = "sha256-d15msuvzITPE9tzuZaJoWFRue77vFSAsaFLSV8e2PRM=";
    };
    date = "2026-08-23";
  };
  fallow = {
    pname = "fallow";
    version = "v3.18.0";
    src = fetchFromGitHub {
      owner = "fallow-rs";
      repo = "fallow";
      rev = "v3.18.0";
      fetchSubmodules = false;
      sha256 = "sha256-ic6jZ/TWqfdKFWDgdB0bXnbAbjmXlw7mKWcenxRNooM=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-ic6jZ_TWqfdKFWDgdB0bXnbAbjmXlw7mKWcenxRNooM=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  g = {
    pname = "g";
    version = "e102a8b8ab8fc5ffd5b12c6b0e1b06c92914896a";
    src = fetchgit {
      url = "https://codeberg.org/ungo/g";
      rev = "e102a8b8ab8fc5ffd5b12c6b0e1b06c92914896a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-sNQchzOsvp+iMpk8deBBJpFR01Ks5ukS8Z/Mr58kVRM=";
    };
    date = "2026-04-26";
  };
  graphify = {
    pname = "graphify";
    version = "v0.9.50";
    src = fetchFromGitHub {
      owner = "safishamsi";
      repo = "graphify";
      rev = "v0.9.50";
      fetchSubmodules = false;
      sha256 = "sha256-RBL86ezqLdf+TDXWW9vWTUCr29pygwlIpCLPyCe5WXA=";
    };
  };
  grompt = {
    pname = "grompt";
    version = "454b177040cd38da0398b2672f74b262d67f65cb";
    src = fetchgit {
      url = "https://codeberg.org/estebxn/grompt";
      rev = "454b177040cd38da0398b2672f74b262d67f65cb";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-PY7xJvn14rI27DVTzJYgJkQ7e9IRPbCXcYVXOhTkWjQ=";
    };
    date = "2026-06-03";
  };
  nano-ffmpeg = {
    pname = "nano-ffmpeg";
    version = "f51b0acc157f96682e2f93a5b994766b039ec2ba";
    src = fetchFromGitHub {
      owner = "dgr8akki";
      repo = "nano-ffmpeg";
      rev = "f51b0acc157f96682e2f93a5b994766b039ec2ba";
      fetchSubmodules = false;
      sha256 = "sha256-4uZ2y+Qe4uMrnpzl8BHQEWFNkhwNBBwoxb5RMnLyGfM=";
    };
    date = "2026-04-25";
  };
  typescript-svelte-plugin = {
    pname = "typescript-svelte-plugin";
    version = "0.3.52";
    src = fetchurl {
      url = "https://registry.npmjs.org/typescript-svelte-plugin/-/typescript-svelte-plugin-0.3.52.tgz";
      sha256 = "sha256-F0psKMVXJw4hSucCUtgHw/47uA0k+sbMqRdhZFTwAFo=";
    };
  };
  unfetch = {
    pname = "unfetch";
    version = "76f2a2fb1ce40b352c505fa3e5e47effa6654246";
    src = fetchgit {
      url = "https://codeberg.org/ungo/unfetch";
      rev = "76f2a2fb1ce40b352c505fa3e5e47effa6654246";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Yv7U6n+xMgFhawGP9mU0h1gjkn4VLTgKTHeNt7Hb0js=";
    };
    date = "2026-03-11";
  };
}
