# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  cord-nvim = {
    pname = "cord-nvim";
    version = "v2.3.20";
    src = fetchFromGitHub {
      owner = "vyfor";
      repo = "cord.nvim";
      rev = "v2.3.20";
      fetchSubmodules = false;
      sha256 = "sha256-9ZPczSPtMls78hBze+tF0pbm9OpSyNc1fAFo4NHg1Tk=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-9ZPczSPtMls78hBze+tF0pbm9OpSyNc1fAFo4NHg1Tk=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  equibop = {
    pname = "equibop";
    version = "ad51504d6dd5a948d0b59327572e219f34c644ae";
    src = fetchFromGitHub {
      owner = "Equicord";
      repo = "Equicord";
      rev = "ad51504d6dd5a948d0b59327572e219f34c644ae";
      fetchSubmodules = false;
      sha256 = "sha256-CnqaVbHv+61/5BTK7dBtpGNpbcZOrTWr4cwr4EOxbFA=";
    };
    date = "2026-04-12";
  };
  unfetch = {
    pname = "unfetch";
    version = "76f2a2fb1ce40b352c505fa3e5e47effa6654246";
    src = fetchgit {
      url = "https://codeberg.org/ungo/unfetch";
      rev = "76f2a2fb1ce40b352c505fa3e5e47effa6654246";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Yv7U6n+xMgFhawGP9mU0h1gjkn4VLTgKTHeNt7Hb0js=";
    };
    date = "2026-03-11";
  };
}
