# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  cord-nvim = {
    pname = "cord-nvim";
    version = "v2.3.20";
    src = fetchFromGitHub {
      owner = "vyfor";
      repo = "cord.nvim";
      rev = "v2.3.20";
      fetchSubmodules = false;
      sha256 = "sha256-9ZPczSPtMls78hBze+tF0pbm9OpSyNc1fAFo4NHg1Tk=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-9ZPczSPtMls78hBze+tF0pbm9OpSyNc1fAFo4NHg1Tk=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  equibop = {
    pname = "equibop";
    version = "81c1be068a05197ded7afe83a8212226f5fc97ba";
    src = fetchFromGitHub {
      owner = "Equicord";
      repo = "Equicord";
      rev = "81c1be068a05197ded7afe83a8212226f5fc97ba";
      fetchSubmodules = false;
      sha256 = "sha256-/XmfFVYSJX6cmVEsvLjyi0Im4jdoJyx4yTz9mTtZFBA=";
    };
    date = "2026-04-24";
  };
  nano-ffmpeg = {
    pname = "nano-ffmpeg";
    version = "b3f01aa076b0fd8c3ff8f71cec69f787ece06095";
    src = fetchFromGitHub {
      owner = "dgr8akki";
      repo = "nano-ffmpeg";
      rev = "b3f01aa076b0fd8c3ff8f71cec69f787ece06095";
      fetchSubmodules = false;
      sha256 = "sha256-gnlYkG2Q/WtkH9x6Mhf7BunYMJPD+ZzZS760JJK6ZwI=";
    };
    date = "2026-04-18";
  };
  unfetch = {
    pname = "unfetch";
    version = "76f2a2fb1ce40b352c505fa3e5e47effa6654246";
    src = fetchgit {
      url = "https://codeberg.org/ungo/unfetch";
      rev = "76f2a2fb1ce40b352c505fa3e5e47effa6654246";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Yv7U6n+xMgFhawGP9mU0h1gjkn4VLTgKTHeNt7Hb0js=";
    };
    date = "2026-03-11";
  };
}
